Correct URL for `DxCore:avr-gcc@7.3.0-atmel3.6.1-azduino8a` archive
The previous URL was that of the page for the file on the GitHub repository website, not the URL of the file download.
This caused Boards Manager to the HTML file of the web page instead of the archive file. That resulted in the platform
installation failing due to the file not passing checksum verification:

```
megaTinyCore:megaavr@2.6.12
Installing DxCore:avr-gcc@7.3.0-atmel3.6.1-azduino8a
Failed to install platform: 'megaTinyCore:megaavr:2.6.12'.
Error: 13 INTERNAL: Cannot install tool DxCore:avr-gcc@7.3.0-atmel3.6.1-azduino8a: testing local archive integrity: testing archive checksum: archive hash differs from hash in index
```